basic:
    name: 'https://www.eckankar.org'
    environments:
        production: 'https://www.eckankar.org'
        staging: 'https://dev.eckankar.org'
        development: ''
    breakpoints:
        - 640
        - 1024
        - 1440
    pages:
        - /
        - /explore/what-is-eckankar
        - /explore/spiritual-teachers
        - /eck-soul-adventure
        - /explore/faqs
        - /explore/toe-calendar
        - /explore/parents-families
        - /experience/hu-the-sound-of-soul
        - /experience/dreams
        - /experience/soul-travel
        - /experience/past-lives
        - /experience/light-and-sound
        - /membership-start
        - /engage/advanced-spiritual-living
        - /engage/eck-soul-adventure-seminars
        - /podcasts-2
        - /eck-soul-adventure-magazine
        - /ebooklets
        - /engage/daily-inspiration
        - /engage/develop-a-daily-practice
        - /engage/find-a-location
        - /contact-us
        - /hu/explore-hu-en
        - /freebook/wisdom
        - /blog
        - /html/Members/books.html
        - /members
        - /eny25-prereg-landing-page
        - /prereg-1
        - /heros-journey
        - /eck-master/sri-harold-klemp
        - /privacy
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ".vim-video iframe\naudio"
    isolate: ''
    delay: 15
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content:
        - { selector: '', type: title }
    login:
        type: none
        click_element: false
        click_element_selector: ''
        login_url: ''
        username: ''
        password: ''
        username_selector: ''
        password_selector: ''
        submit_selector: ''
        after_login_selector: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
